### ISSUE TITLE
monetd default data directory path

### ISSUE THREAD

**Issue by danu30** [mosaicnetworks/monetd#11]
Currently the data directory path for `monetd` is:

-   Linux - `~/.monet`
-   Mac OS - `~/Library/MONET`
-   Windows - `~/AppData/Roaming/MONET`

While these are the correct locations, the name of the directory should be class case to remain within convention for Windows and Mac OS.

They should be renamed to:

-   Linux - `~/.monet`
-   Mac OS - `~/Library/Monet`
-   Windows - `~/AppData/Roaming/Monet`

**Comment by jonknight73** [comment]
This is a single line change to src/configuration/const.go 
The const defintion of MonetdTomlDirCaps in approx line 23. 

It is a trivial change to make, but it is a breaking change for MacOS. Windows is case insensitive unless specifically changed to be so - and even then, it was only available since April 2018 (more here: https://www.howtogeek.com/354220/how-to-enable-case-sensitive-folders-on-windows-10/ )

**Comment by arrivets** [comment]
Fixed in e22f9d8bb278377e2125bd18ccbe4cab8eaffa70
